// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRZSUHAfCkdzaEcc9yQHPGNG00OMY-TbA',
    appId: '1:623355973363:web:9479d08b3c9ad839933186',
    messagingSenderId: '623355973363',
    projectId: 'quanlynhanvien-92e2c',
    authDomain: 'quanlynhanvien-92e2c.firebaseapp.com',
    storageBucket: 'quanlynhanvien-92e2c.appspot.com',
    measurementId: 'G-XFTW6W7EJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4s5mv9Fu14HzT2oVZCcLcACOO6ekDDh4',
    appId: '1:623355973363:android:200b8bc6dec500c7933186',
    messagingSenderId: '623355973363',
    projectId: 'quanlynhanvien-92e2c',
    storageBucket: 'quanlynhanvien-92e2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBBQ5YkUCW0Y2qi0t1Rt42B-ToNKM__M',
    appId: '1:623355973363:ios:0a98afe072f9059e933186',
    messagingSenderId: '623355973363',
    projectId: 'quanlynhanvien-92e2c',
    storageBucket: 'quanlynhanvien-92e2c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsBBQ5YkUCW0Y2qi0t1Rt42B-ToNKM__M',
    appId: '1:623355973363:ios:b2bfb9d88c900816933186',
    messagingSenderId: '623355973363',
    projectId: 'quanlynhanvien-92e2c',
    storageBucket: 'quanlynhanvien-92e2c.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
